#!/usr/bin/env bun
// index.ts — (re)generate apps.index.json, a greppable registry of the test
// library: every registered app, its window title, and the component test files
// + suites + test names it contains.
//
// Usage:  bun scripts/index.ts            # write apps.index.json + print summary
//         bun scripts/index.ts --check    # exit 1 if the index is stale
//
// The index is derived purely from apps/<slug>/ — author tests, run this, commit
// both. It is the per-app "component library" view the harness indexes for you.

import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const APPS = join(ROOT, "apps");
const OUT = join(ROOT, "apps.index.json");

export interface ComponentEntry { file: string; suites: string[]; tests: string[]; }
export interface AppEntry { slug: string; name: string; windowTitle: string; dir: string; components: ComponentEntry[]; }
export interface Index { note: string; apps: AppEntry[]; }

function firstString(call: string): string | null {
  const m = call.match(/['"`]([^'"`]+)['"`]/);
  return m ? m[1] : null;
}

async function scanApp(slug: string): Promise<AppEntry | null> {
  const dir = join(APPS, slug);
  if (!(await stat(dir).then((s) => s.isDirectory()).catch(() => false))) return null;

  // window title + name from app.config.ts
  let windowTitle = "", name = slug;
  const cfgPath = join(dir, "app.config.ts");
  if (await stat(cfgPath).then(() => true).catch(() => false)) {
    const cfg = await readFile(cfgPath, "utf8");
    windowTitle = cfg.match(/windowTitle:\s*['"`]([^'"`]+)['"`]/)?.[1] ?? "";
    name = cfg.match(/name:\s*['"`]([^'"`]+)['"`]/)?.[1] ?? slug;
  }

  // component test files
  const compDir = join(dir, "components");
  const files = (await readdir(compDir).catch(() => [])).filter((f) => f.endsWith(".test.ts")).sort();
  const components: ComponentEntry[] = [];
  for (const file of files) {
    const src = await readFile(join(compDir, file), "utf8");
    const suites: string[] = [];
    const tests: string[] = [];
    for (const line of src.split("\n")) {
      const t = line.trim();
      if (t.startsWith("describe(")) { const s = firstString(t); if (s) suites.push(s); }
      else if (t.startsWith("test(") || t.startsWith("test.if(") || t.startsWith("it(")) {
        const s = firstString(t.replace(/^test\.if\([^)]*\)/, "")); if (s) tests.push(s);
      }
    }
    components.push({ file: `components/${file}`, suites, tests });
  }
  return { slug, name, windowTitle, dir: `apps/${slug}`, components };
}

/** Compute the index from disk WITHOUT writing it. */
export async function computeIndex(): Promise<Index> {
  const slugs = (await readdir(APPS).catch(() => []))
    .filter((d) => !d.startsWith("_") && !d.startsWith("."))
    .sort();
  const apps: AppEntry[] = [];
  for (const slug of slugs) { const a = await scanApp(slug); if (a) apps.push(a); }
  return { note: "Generated by `bun scripts/index.ts` — do not edit by hand.", apps };
}

/** Compute the index and write apps.index.json. */
export async function buildIndex(): Promise<Index> {
  const index = await computeIndex();
  await writeFile(OUT, JSON.stringify(index, null, 2) + "\n");
  return index;
}

function summarize(idx: Index): string {
  const lines: string[] = [];
  for (const a of idx.apps) {
    const n = a.components.reduce((acc, c) => acc + c.tests.length, 0);
    lines.push(`${a.slug}  ("${a.windowTitle}")  — ${a.components.length} files, ${n} tests`);
    for (const c of a.components) lines.push(`  ${c.file}: ${c.tests.length} tests [${c.suites.join(", ")}]`);
  }
  return lines.join("\n");
}

if (import.meta.main) {
  if (process.argv.includes("--check")) {
    const fresh = await computeIndex();
    const onDisk = await readFile(OUT, "utf8").catch(() => "");
    const expected = JSON.stringify(fresh, null, 2) + "\n";
    if (onDisk !== expected) { console.error("apps.index.json is stale — run: bun scripts/index.ts"); process.exit(1); }
    console.log("apps.index.json up to date");
  } else {
    const fresh = await buildIndex();
    console.log(summarize(fresh));
    console.log(`\nwrote ${fresh.apps.length} app(s) -> apps.index.json`);
  }
}
